name: Run tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test
      run: mvn test
    - name: Deploy
      uses: samuelmeuli/action-maven-publish@v1
      with:
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        maven_args: "-s settings.xml"
        maven_profiles: "nexus"
