name: Run tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test
      run: mvn test

